
  name: dbt Snowflake Pipeline

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    dev:
      runs-on: ubuntu-latest
      env:
        ENVIRONMENT: production
        SNOWFLAKE_ACCOUNT: ${{ secrets.PRODUCTION_SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.PRODUCTION_SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.PRODUCTION_SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.PRODUCTION_SNOWFLAKE_ROLE }}
        SNOWFLAKE_DATABASE: ${{ secrets.PRODUCTION_SNOWFLAKE_DATABASE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.PRODUCTION_SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.PRODUCTION_SNOWFLAKE_SCHEMA }}
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Install dependencies
          run: |
            pip install dbt-snowflake
  
        - name: Configure dbt profiles.yml
          run: |
            mkdir -p ~/.dbt
            echo "default:" >> ~/.dbt/profiles.yml
            echo "  outputs:" >> ~/.dbt/profiles.yml
            echo "    production:" >> ~/.dbt/profiles.yml
            echo "      type: snowflake" >> ~/.dbt/profiles.yml
            echo "      account: ${{ secrets.PRODUCTION_SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
            echo "      user: ${{ secrets.PRODUCTION_SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
            echo "      password: ${{ secrets.PRODUCTION_SNOWFLAKE_PASSWORD }}" >> ~/.dbt/profiles.yml
            echo "      role: ${{ secrets.PRODUCTION_SNOWFLAKE_ROLE }}" >> ~/.dbt/profiles.yml
            echo "      database: ${{ secrets.PRODUCTION_SNOWFLAKE_DATABASE }}" >> ~/.dbt/profiles.yml
            echo "      warehouse: ${{ secrets.PRODUCTION_SNOWFLAKE_WAREHOUSE }}" >> ~/.dbt/profiles.yml
            echo "      schema: ${{ secrets.PRODUCTION_SNOWFLAKE_SCHEMA }}" >> ~/.dbt/profiles.yml
  
        - name: Run dbt
          env:
            DBT_PROFILES_DIR: ~/.dbt
          run: |
            dbt run -h
            dbt run --profiles-dir $DBT_PROFILES_DIR
  
